import type { Reading } from '@/lib/types'

const DEMO_ACADEMIC_YEAR = '2024-2025'

export const DEMO_CANON_NARRATIVE = "Athena\u2019s third-grade canon traces a deliberate path from fable to allegory. She opened the year with Alice and Black Beauty \u2014 narrators she could argue with \u2014 and closed it with Lamb\u2019s Tales from Shakespeare and the Arabian Nights, texts that asked her to sit inside nested frames. The d\u2019Aulaires\u2019 Book of Greek Myths became her anchor: she returned to it unprompted all year and began citing its figures in her own writing. Her most unusual instinct, for a reader this age, is to compare across books \u2014 she linked Gerda\u2019s loyalty in The Snow Queen to Wilbur\u2019s in Charlotte\u2019s Web without any prompting. Next year we\u2019ll push her toward Kipling\u2019s longer work and a first abridged encounter with Dickens."

export const DEMO_READINGS: Reading[] = [
  {
    id: 'demo-1', schoolId: '', studentId: 'demo-athena',
    title: 'Alice in Wonderland', author: 'Lewis Carroll',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 1,
    whyChosen: 'Chose it after seeing the Tenniel illustrations at the library — wanted to know "why the rabbit looked so worried."',
    valuesSkills: null, pageCount: 192,
    teacherNotes: 'Athena tracked Alice\u2019s shifts in scale as a metaphor for growing up; unusually sharp close reading for a third grader.',
    readingDifficulty: 'stretch', studentRating: 5,
    dateStarted: '2024-09-09', dateFinished: '2024-09-28',
    keyQuote: '"It\u2019s no use going back to yesterday, because I was a different person then."',
    curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-2', schoolId: '', studentId: 'demo-athena',
    title: "Grimm's Fairy Tales", author: 'Jacob & Wilhelm Grimm',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 2,
    whyChosen: 'Wanted to compare the "real" Grimm versions to the Disney ones she knew.',
    valuesSkills: null, pageCount: 288,
    teacherNotes: 'Asked why the older tales are darker — led to a class discussion on oral storytelling and moral instruction.',
    readingDifficulty: 'on_level', studentRating: 4,
    dateStarted: '2024-10-01', dateFinished: '2024-10-22',
    keyQuote: null, curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-3', schoolId: '', studentId: 'demo-athena',
    title: 'Black Beauty', author: 'Anna Sewell',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 3,
    whyChosen: 'Loves horses; asked for it specifically after a barn visit with her grandfather.',
    valuesSkills: null, pageCount: 245,
    teacherNotes: 'First book Athena connected emotionally to an animal narrator. Wrote a one-paragraph response on her own, unprompted.',
    readingDifficulty: 'on_level', studentRating: 5,
    dateStarted: '2024-10-25', dateFinished: '2024-11-14',
    keyQuote: '"We call them dumb animals, and so they are, for they cannot tell us how they feel, but they do not suffer less because they have no words."',
    curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-4', schoolId: '', studentId: 'demo-athena',
    title: "Charlotte's Web", author: 'E. B. White',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 4,
    whyChosen: 'Picked it after her brother read it aloud the previous summer; wanted to "read it properly" herself.',
    valuesSkills: null, pageCount: 184,
    teacherNotes: 'Athena noticed White\u2019s restraint in the final chapters — she told the class, "he doesn\u2019t have to say Wilbur is sad, because the barn is quiet." A remarkable observation about literary implication.',
    readingDifficulty: 'on_level', studentRating: 5,
    dateStarted: '2024-11-18', dateFinished: '2024-12-06',
    keyQuote: '"It is not often that someone comes along who is a true friend and a good writer. Charlotte was both."',
    curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-5', schoolId: '', studentId: 'demo-athena',
    title: "D'Aulaires' Book of Greek Myths", author: 'Ingri & Edgar Parin d\u2019Aulaire',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 5,
    whyChosen: 'Drawn in by her own name — wanted to know "who Athena really was."',
    valuesSkills: null, pageCount: 192,
    teacherNotes: 'Became a ready reference for Athena all year. She began citing myths in her own writing (see the "Piglet flood" retelling in Composition). Strong retention of genealogy and epithets.',
    readingDifficulty: 'stretch', studentRating: 5,
    dateStarted: '2024-12-09', dateFinished: '2025-01-10',
    keyQuote: '"She sprang fully grown from the forehead of Zeus, with a mighty battle cry."',
    curriculumConnection: 'history', createdAt: '',
  },
  {
    id: 'demo-6', schoolId: '', studentId: 'demo-athena',
    title: 'The Snow Queen', author: 'Hans Christian Andersen',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 6,
    whyChosen: 'Read it in the winter after the first big snow.',
    valuesSkills: null, pageCount: 96,
    teacherNotes: 'Compared Gerda\u2019s loyalty to Wilbur\u2019s — cross-text thinking we rarely see this early.',
    readingDifficulty: 'on_level', studentRating: 4,
    dateStarted: '2025-01-13', dateFinished: '2025-01-27',
    keyQuote: null, curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-7', schoolId: '', studentId: 'demo-athena',
    title: 'The Lion, the Witch and the Wardrobe', author: 'C. S. Lewis',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 7,
    whyChosen: 'Chose it after a classmate mentioned Narnia at recess — wanted to be "part of the conversation."',
    valuesSkills: null, pageCount: 208,
    teacherNotes: 'Athena identified Aslan\u2019s sacrifice as a "story people have told before" and asked thoughtful questions about allegory. We kept the conversation age-appropriate, but her instinct for layered meaning was striking.',
    readingDifficulty: 'on_level', studentRating: 5,
    dateStarted: '2025-01-30', dateFinished: '2025-02-18',
    keyQuote: '"Courage, dear heart."',
    curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-8', schoolId: '', studentId: 'demo-athena',
    title: 'Charlie and the Chocolate Factory', author: 'Roald Dahl',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 8,
    whyChosen: 'Comfort read between heavier books.',
    valuesSkills: null, pageCount: 160,
    teacherNotes: 'Asked whether Dahl was "being mean on purpose" to the other children — a productive entry point to talking about satire.',
    readingDifficulty: 'below_level', studentRating: 4,
    dateStarted: '2025-02-20', dateFinished: '2025-03-02',
    keyQuote: null, curriculumConnection: 'free_choice', createdAt: '',
  },
  {
    id: 'demo-9', schoolId: '', studentId: 'demo-athena',
    title: 'The Jungle Book', author: 'Rudyard Kipling',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 9,
    whyChosen: 'Picked after the Greek myths — interested in "rules animals live by."',
    valuesSkills: null, pageCount: 256,
    teacherNotes: 'Struggled with Kipling\u2019s vocabulary at first; by the second week was reading aloud with confidence and inflection.',
    readingDifficulty: 'stretch', studentRating: 4,
    dateStarted: '2025-03-05', dateFinished: '2025-03-28',
    keyQuote: '"We be of one blood, ye and I."',
    curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-10', schoolId: '', studentId: 'demo-athena',
    title: 'Homer Price', author: 'Robert McCloskey',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 10,
    whyChosen: 'Teacher recommendation after the Jungle Book — wanted something lighter and American.',
    valuesSkills: null, pageCount: 149,
    teacherNotes: 'Enjoyed the absurdist donut-machine chapter enough to read it aloud to the class. Early sign of comic timing.',
    readingDifficulty: 'below_level', studentRating: 4,
    dateStarted: '2025-03-31', dateFinished: '2025-04-11',
    keyQuote: null, curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-11', schoolId: '', studentId: 'demo-athena',
    title: 'Tales from Shakespeare', author: 'Charles & Mary Lamb',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 11,
    whyChosen: 'Asked for "a harder book, please" after Homer Price.',
    valuesSkills: null, pageCount: 320,
    teacherNotes: 'Worked through "A Midsummer Night\u2019s Dream" and "The Tempest" — retained character names and the shape of each plot a full month later. Began to ask about "real" Shakespeare.',
    readingDifficulty: 'stretch', studentRating: 5,
    dateStarted: '2025-04-14', dateFinished: '2025-05-09',
    keyQuote: '"We are such stuff as dreams are made on."',
    curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-12', schoolId: '', studentId: 'demo-athena',
    title: 'Aladdin and the Arabian Nights', author: 'Andrew Lang (ed.)',
    academicYear: DEMO_ACADEMIC_YEAR, completed: true, sortOrder: 12,
    whyChosen: 'Interested in frame narratives after "Tales from Shakespeare."',
    valuesSkills: null, pageCount: 224,
    teacherNotes: 'Drew a diagram on her own showing "stories inside stories" — first time she mapped narrative structure visually.',
    readingDifficulty: 'on_level', studentRating: 4,
    dateStarted: '2025-05-12', dateFinished: '2025-06-02',
    keyQuote: null, curriculumConnection: 'literature', createdAt: '',
  },
  {
    id: 'demo-13', schoolId: '', studentId: 'demo-athena',
    title: 'Guns for General Washington', author: 'Seymour Reit',
    academicYear: DEMO_ACADEMIC_YEAR, completed: false, sortOrder: 13,
    whyChosen: 'Summer bridge selection into fourth grade — tied to her interest in the American Revolution.',
    valuesSkills: null, pageCount: 157,
    teacherNotes: 'In progress. First nonfiction chapter book; we\u2019re watching how she handles sustained expository prose.',
    readingDifficulty: 'stretch', studentRating: null,
    dateStarted: '2025-06-10', dateFinished: null,
    keyQuote: null, curriculumConnection: 'history', createdAt: '',
  },
]
